# Generated by Django 4.1.7 on 2023-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='cardapio/%Y/%m')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco', models.FloatField()),
            ],
        ),
    ]
