# Generated by Django 4.1.7 on 2023-04-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cardapio/%Y/%m'),
        ),
    ]
