# Generated by Django 4.1.7 on 2023-04-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0002_alter_pizza_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTamanhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cardapio.pizza')),
            ],
        ),
    ]
