# Generated by Django 4.1.7 on 2023-04-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0003_pizzatamanhos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzatamanhos',
            options={'verbose_name': 'Tamanhos de Pizza'},
        ),
    ]
