# Generated by Django 4.1.7 on 2023-04-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_cliente_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='usuario',
        ),
    ]
