# Generated by Django 4.1.7 on 2023-04-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_cliente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
    ]
