# Generated by Django 4.1.7 on 2023-04-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_cliente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
